### ISSUE TITLE
[#10] Eslint 관련 이슈

### ISSUE THREAD

**Issue by intersoom** [Soongmile/Soongmile-FE#10]
## Issue: 🐞 BUG
lint 적용 안되는 문제 발생
- [x] 함수 방식 통일
- [x] 린트 자동 적용되게끔

**Comment by intersoom** [comment]
@seocylucky 
eslint 코드 수정 관련해서 comment 달아뒀어요! 참고해주세요 :)
추가적으로 저는 vscode 설정 추가해서 lint 자동 수정되게끔 해뒀어요! 타입스크립트 관련 설정이 제대로 안되어있어서 적용안되는 것 같아요
만약에 안되시면 말씀해주세용~ 제 세팅 파일 보여드릴게욥

**Comment by seocylucky** [comment]
아이코오,, 제가 세팅을 제대로 안해놨어서 발생한 문제로군요.... 코드 확인했습니당ㅜㅜㅜㅜ!!
